Still not completely ready and working.
'make run' shows the start screen properly again.

'make test' (PYGLET_SHADOW_WINDOW=0) still fails, however we have an improvement, as block-initialization finishes successfully now (so gl.current_context is defined now) and it crashes in nature-initialization (cause unknown yet).

We have an improvement, because if 'G.delayed_inits()' is enabled before the 'super()' call in 'main.py' the old error is shown again, which means, it crashes already in block initialization with:

run init blocks._init
/usr/lib/pymodules/python2.7/pyglet/gl/gl_info.py:114: UserWarning: No GL context created yet.
  warnings.warn('No GL context created yet.')
Traceback (most recent call last):
  File "./main.py", line 171, in <module>
    main(options)
  File "./main.py", line 140, in main
    window = Window(resizable=True, vsync=False)
  File "./main.py", line 36, in __init__
    G.delayed_inits()
  File "/git/git/Minecraft.GITHUB/globals.py", line 400, in delayed_inits
    i()
  File "/git/git/Minecraft.GITHUB/globals.py", line 382, in once
    f(sys.modules[f.__module__])
  File "/git/git/Minecraft.GITHUB/blocks.py", line 1717, in _init
    M.crack_textures = CrackTextureBlock()
  File "/git/git/Minecraft.GITHUB/blocks.py", line 1709, in __init__
    self.group = TextureGroupIndividual(texture_name)
  File "/git/git/Minecraft.GITHUB/blocks.py", line 62, in __init__
    subtex = atlas.add(BLOCK_TEXTURE_DIR[name].get_region(0,0,texture_size,texture_size))
  File "/usr/lib/pymodules/python2.7/pyglet/image/atlas.py", line 207, in add
    self.texture.blit_into(img, x, y, 0)
  File "/usr/lib/pymodules/python2.7/pyglet/image/__init__.py", line 1743, in blit_into
    self.owner.blit_into(source, x + self.x, y + self.y, z + self.z)
  File "/usr/lib/pymodules/python2.7/pyglet/image/__init__.py", line 1633, in blit_into
    source.blit_to_texture(self.target, self.level, x, y, z)
  File "/usr/lib/pymodules/python2.7/pyglet/image/__init__.py", line 927, in blit_to_texture
    if gl.current_context._workaround_unpack_row_length:
AttributeError: 'NoneType' object has no attribute '_workaround_unpack_row_length'